name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: 'ako-oak/llama2-finetuned-mindsdb'  # Your HF repo ID
          repo_type: 'model'
          hf_token: ${{ secrets.HF_TOKEN }}
